col=linspecer(4);
plot(N_list,E0_exact./N_list,'o','MarkerFaceColor',col(1,:),'MarkerEdgeColor',col(1,:),'MarkerSize',6);
hold on;
plot(N_list2,(E0_mps/4)./N_list2,'^','MarkerFaceColor',col(2,:),'MarkerEdgeColor',col(2,:),'MarkerSize',4);
% hold on;
% plot(N_list,E1_exact,'-^','MarkerFaceColor',col(3,:),'MarkerEdgeColor',col(3,:),'MarkerSize',4);
% hold on;
% plot(N_list2,E1_mps/4,'-s','MarkerFaceColor',col(4,:),'MarkerEdgeColor',col(4,:),'MarkerSize',4);
set(gca,'fontsize',14);
box on;
set(gcf,'color','w');
legend('exact','MPS');